INSERT role(name)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS(SELECT name FROM role WHERE name = 'ROLE_ADMIN');

INSERT role(name)
SELECT 'ROLE_USER'
WHERE NOT EXISTS(SELECT name FROM role WHERE name = 'ROLE_USER');
